### ISSUE TITLE
Inconsistent response codes

### ISSUE THREAD

**Issue by derrandz** [buildwithgrove/portal-api#111]
```
  // The gateway constantly responds with 200
  // and responds with errors in response.data
  // in a non-consistent form.
  // So can't rely on response code
 ```

**Comment by nymd** [comment]
If the error in the response data is in a properly formatted JSON response then the API is technically doing it's job by returning the relay. There is code in the API to catch these properly formatted JSON errors:

https://github.com/pokt-foundation/portal-api/blob/4dd8faa27550e3ee3af90c7903a6d8a4d52be87f/src/services/pocket-relayer.ts#L430

It is hacky. If it is not catching this case for this issue, can you give a full example of the request/response?

**Comment by derrandz** [comment]
Indeed, that's what an accepted behavior of a relayer endpoint should look like. I must've lost context as I was expecting errors whereas now --since it's a relay, they will be part of the data relayed.

This is now to be reversed, this is an issue of the error handling code at the datasource in the wallet and explorer and not the portal-api.

I will close this issue in favor of the other two when I created them.

- [ ] Reference this issue and create its reverse in wallet
- [ ] Do the same for the explorer
- [ ] Close this issue.

**Comment by rem1niscence** [comment]
Are we sure we want all the responses to be checked on the body and not some on the response code? for example as of right now relaying a non existent app will return 200 but a message with "Entity not found" which could be semantically misleading and the relay didn't even happen
