### ISSUE TITLE
Dispatcher list going faulty in some regions at random times

### ISSUE THREAD

**Issue by nymd** [buildwithgrove/portal-api#227]
Investigate why the dispatcher list sometimes fails and a region will constantly throw

`[Unable to readRandomDispatcher(), No dispatcher's available.] `

https://app.datadoghq.eu/logs?query=readRandomDispatcher&agg_m=count&agg_q=region&agg_t=count&analyticsOptions=%22bars%22&index=&sort_m=&sort_t=&top_n=10&top_o=top&viz=timeseries&from_ts=1628952228814&to_ts=1629557028814&live=true

**Comment by crisog** [comment]
https://github.com/pokt-network/pocket-js/issues/429
