### ISSUE TITLE
Lost request information with new log format

### ISSUE THREAD

**Issue by nymd** [buildwithgrove/portal-api#308]
https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E0$257Estart$257E-3600$257EtimeType$257E$2527RELATIVE$257Eunit$257E$2527seconds$257EeditorString$257E$2527fields*20*40timestamp*2c*20*40message*0a*7c*20filter*20*40message*20like*20*2f0APy5B5DYJ*2f*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020$257EisLiveTail$257Efalse$257EqueryId$257E$2527339f154e-f862-497a-9957-bba8b697ef96$257Esource$257E$2528$257E$2527*2fecs*2fgateway$2529$2529

We cannot see what the actual request is now; this may have been my fault when I reduced the log verbosity.

**Comment by crisog** [comment]
Closed by #309 and #315.
