### ISSUE TITLE
Timeouts are not respected somewhere system wide

### ISSUE THREAD

**Issue by nymd** [buildwithgrove/portal-api#323]
1. Timeouts on load balancers seem to not be respected -- always timing out after 5000 ms

2. We should add a default timeout on blockchains so that if one isn't set on the LB, it goes to the Blockchain record's timeout

**Comment by crisog** [comment]
Isn't this solved already @rem1niscence ?

**Comment by rem1niscence** [comment]
only point one, feel free to take point two if you want
