### ISSUE TITLE
Use JSON RPC standard to return responses

### ISSUE THREAD

**Issue by crisog** [buildwithgrove/portal-api#495]
The API connects clients with blockchain nodes using Pocket Network Protocol. 

Since blockchain nodes use JSON RPC, we should also use this standard to return responses that come from the API itself; such as the "Relays attempts exhasted" error.

Why?
Some of the clients (web3.js as example) expects a JSON RPC response for communication. If we are relaying the node's response its all good, however, if something unexpected happens and we return a message from the API as a plain JSON, web3.js will throw.

**Comment by crisog** [comment]
I propose these reserved errors; starting from 50 to avoid overlapping node rpc reserved errors if any.
|  Code  | Message  | Meaning  | Category  |
|---|---|---|---|
|  -32050 | Relay attempts exhausted  | Request failed to be served  | non-standard  |
|  -32051 | Overall timeout exceeded  | Request took too long | non-standard  |
|  -32052 | Invalid domain  | Invalid blockchain domain | non-standard  |
|  -32053 | Method cannot be served over HTTPS  | We do not support WebSockets yet | non-standard  |
|  -32054 | Loader balancer not found  | Not found in database | non-standard  |
|  -32055 | No application found in load balancer  | Not found in database | non-standard  |
|  -32056 | Application not found  | Not found in database | non-standard  |
|  -32057 | Incorrect blockchain  | Not found in database | non-standard  |
|  -32058 | Load Balancer configuration invalid  | Load balancer misconfigured in database | non-standard  |
|  -32059 | Secret key does not match  | Application's secret key doesn't match | non-standard  |
|  -32060 | Whitelist origin check failed | Application configuration doesn't allow specified origin | non-standard  |
|  -32061 | Whitelist user agent failed | Application configuration doesn't allow specified user-agent | non-standard  |
|  -32062 | Try again with a explicit block number  | eth_getLogs Limit Error | non-standard  |
|  -32063 | Please use an explicit block number instead of 'latest' | eth_getLogs Limit Error | non-standard  |
|  -32064 | You cannot query logs for more than X amount of blocks | eth_getLogs Limit Error | non-standard  |
|  -32065 | Node returned an invalid response | - | non-standard  |

**Comment by nymd** [comment]
If these don't overlap with existing EVM errors, approved.
