### ISSUE TITLE
Use pocket prefix on JSON-RPC response ids

### ISSUE THREAD

**Issue by crisog** [buildwithgrove/portal-api#505]
As you know, we know return API errors using the JSON-RPC standard. We created a table for error codes on #495 that don't overlap with current node software JSON-RPC custom errors.

A sample response now would be:
```
{
    "jsonrpc": "2.0",
    "id": 1, 
    "error": {
        "message": "Load balancer not found",
        "code": -32054
    }
}
```

Since there's no enforcement in the JSON-RPC standard on `id` property other than returning the same `id` placed on the request object. I suggest using "pokt" as prefix for the JSON-RPC response. It would look like this:
```
{
    "jsonrpc": "2.0",
    "id": "pokt-${IdFromReq}",
    "error": {
        "message": "Load balancer not found",
        "code": -32054
    }
}
```

**Comment by nymd** [comment]
Disagree; ID is used for ordering by clients. This would throw off the correlation between a request made and the error returned.
