### ISSUE TITLE
Cherry picker top bucket smearing

### ISSUE THREAD

**Issue by nymd** [buildwithgrove/portal-api#552]
The top bucket of the cherry picker should be more inclusive -- if you have an medianSuccessLatency of below a certain threshold, you should always be in the top bucket for random picking. That threshold should have a default of maybe 100ms but then be configurable in the database per chain.

**Comment by nymd** [comment]
There are situations with the picker where the nodes' median success latency looks like this:

- 30ms
- 50ms
- 60ms
- 300ms
- 400ms

The top 3 nodes are obviously in the same city or very close to the API but the 3's response time is still double that of node 1. This is very significant in the picker's eyes and currently the 3 node will get much fewer relays.

However the difference in real world usage between 30ms and 60ms is minimal and nodes 1 through 3 should be equally rewarded for providing top tier service.

**Comment by rem1niscence** [comment]
can this be closed?
