### ISSUE TITLE
[BUG REPORT] Footprint Avax Endpoint not working

### ISSUE THREAD

**Issue by bigbrainpokt** [buildwithgrove/portal-api#705]
When Footprint switches endpoint to Avax Mainnet the following error message is displayed:
 {"jsonrpc":"2.0","id":1,"error":{"message":"Internal JSON-RPC error.","code":-32603 }}" 
![tg_image_366697573](https://user-images.githubusercontent.com/97472080/155759978-584ecb36-742f-4a80-9f25-7359a723cd28.jpeg)

Also this

curl -X POST --user-agent "curl" -H "Content-Type: application/json" --user :6bb95bfb648b8812e8dd9daa0fbdfe20 --data '{"id": 1, "method": "eth_blockNumber", "params": [], "jsonrpc":"2.0"}' "https://avax-mainnet.gateway.pokt.network/v1/lb/6216f4c3c2d2890039aaa92b"

**Comment by blockjoe** [comment]
This is because EVM calls on Avalanche need to specify the `/ext/bc/C/rpc` route that an Avalanche node expects immediately after the Portal ID.
