### ISSUE TITLE
Sync check needs to have a variable syncAllowance

### ISSUE THREAD

**Issue by nymd** [buildwithgrove/portal-api#73]
Field is in the db but needs to be implemented in code to allow variable sync allowances per chain

**Comment by crisog** [comment]
I see that there was an attempt to add `syncAllowance` per chain at this commit (https://github.com/pokt-foundation/portal-api/commit/c7293949c04928dd278d565c69759c5cb60f0c01). 

What was the bug?

**Comment by crisog** [comment]
> Field is in the db but needs to be implemented in code to allow variable sync allowances per chain

I see that there was an attempt to add `syncAllowance` per chain at this commit (https://github.com/pokt-foundation/portal-api/commit/7e8f838cd6458bec4ad4b93384fcc7e8a3985246) but was removed shortly after. 

What was the bug (if any)?

**Comment by nymd** [comment]
There was a bug in the way that I was pulling multiple fields from the blockchain. That bug is fixed now as you can see it's pulling multiple fields like the sync check and sync check path. 

If you wanted to take this as a first bug, I think the development environment is in a good shape now, and it would be fantastic if you tried it.

**Comment by crisog** [comment]
> There was a bug in the way that I was pulling multiple fields from the blockchain. That bug is fixed now as you can see it's pulling multiple fields like the sync check and sync check path.
> 
> If you wanted to take this as a first bug, I think the development environment is in a good shape now, and it would be fantastic if you tried it.

Sure, I'm gonna give it a try now 👍🏽
