### ISSUE TITLE
Updated .env.example file

### ISSUE THREAD

**Issue by nodiesBlade** [buildwithgrove/portal-api#800]
**Describe the bug**
I'm trying to load up a localnet stack, but the env files are outdated. So far, I've noticed the `PSQL_CONNECTIONS` and `ARCHIVAL_CHAINS` are missing.

Also, aws creds are required. What do we need them for?

**Comment by nodiesBlade** [comment]
![image](https://user-images.githubusercontent.com/99137075/160923868-9a023567-a585-44a5-b701-22d8f8748766.png)

After providing these credentials (mocked the aws creds), the gateway server was able to load up..

**Comment by crisog** [comment]
I've updated these, thanks for reporting!
