### ISSUE TITLE
[BUG REPORT] Not all user error messages are included

### ISSUE THREAD

**Issue by addiaddiaddi** [buildwithgrove/portal-api#862]
**Describe the bug**
A change was made to the userError function since there are some -32k errors that are of the fault of the node operator; however, not all of the user errors are listed in the function, causing node runners to be unfairly penalized, it would appear. 

**To Reproduce**
Check error logs and compare user errors to those listed in the function. 

https://github.com/pokt-foundation/portal-api/blob/076af0c947ef8927dd65533354689eb99a196552/src/utils/errors.ts#L4

See some errrors here that aren't listed above 
https://prnt.sc/OjHJ2_AdjJRt

**Expected behavior**
Node operators should not be penalized for serving these nodes; however, it appears that they are.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/OjHJ2_AdjJRt)

**Comment by Andrew-Pohl** [comment]
There are some additional -32000 errors that also need considering

- ‘no suitable peers available’ - these can occur when trying to server archive data from a non archived node
-  ‘gas required exceeds allowance' - self explanatory the gas required is greater than the block limit 
- 'fee cap less than block base fee' - EIP1559 related
- 'pending blocks are not supported' - if the node doesn't support pending 
- 'nonce too low' - trying to downgrade a nonce
- 'missing block number' 
- 'sender not an eoa: address' - EIP-3607

I'm sure there are loads more I'm missing here!

**Comment by crisog** [comment]
> **Describe the bug** A change was made to the userError function since there are some -32k errors that are of the fault of the node operator; however, not all of the user errors are listed in the function, causing node runners to be unfairly penalized, it would appear.
> 
> **To Reproduce** Check error logs and compare user errors to those listed in the function.
> 
> https://github.com/pokt-foundation/portal-api/blob/076af0c947ef8927dd65533354689eb99a196552/src/utils/errors.ts#L4
> 
> See some errrors here that aren't listed above https://prnt.sc/OjHJ2_AdjJRt
> 
> **Expected behavior** Node operators should not be penalized for serving these nodes; however, it appears that they are.
> 
> **Screenshots** [If applicable, add screenshots to help explain your problem.](https://prnt.sc/OjHJ2_AdjJRt)

You are right. If all of the possible EVM user errors are not there, nodes could be penalized (and are being penalized) which is not OK. The issue with the current code is the approach, there is an rather infinite amount variety of errors across EVM forks - and each new that comes will bring new errors. Taking this in consideration, it's not very smart to filter by their messages.

A better approach (discussed with Addison off-github) is assuming user error, and narrowing down node errors which are way less. I'm currently working on a better implementation.

Thanks for the additional insight  @Andrew-Pohl.

**Comment by crisog** [comment]
Deployed at https://github.com/pokt-foundation/portal-api/commit/191442d6219082160e164069b74c36491cdb1f2d.
